//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply_Loan
    {
        public int CUSTOMER_ID { get; set; }
        public string CustomerName { get; set; }
        public decimal LoanAmount { get; set; }
        public string LoanType { get; set; }
        public int Tenure { get; set; }
        public int CreditLimit { get; set; }
        public string StatusType { get; set; }
    }
}
