//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_EMPLOYEE
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public Nullable<decimal> Contact_Number { get; set; }
        public string Email { get; set; }
        public string Employee_Type { get; set; }
        public string Password { get; set; }
    }
}
