//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.LOAN_DETAILS = new HashSet<LOAN_DETAILS>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string PAN_NUMBER { get; set; }
        public long AADHAR_NUMBER { get; set; }
        public long CONTACT_NUMBER { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_CREDIT_DATE { get; set; }
        public string PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN_DETAILS> LOAN_DETAILS { get; set; }
    }
}
