//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Services.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LMS_DBEntities1 : DbContext
    {
        public LMS_DBEntities1()
            : base("name=LMS_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Apply_Loan> Apply_Loan { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BANK_EMPLOYEE> BANK_EMPLOYEE { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Details> Customer_Details { get; set; }
        public virtual DbSet<Interest_Rate_Details> Interest_Rate_Details { get; set; }
        public virtual DbSet<LOAN_DETAILS> LOAN_DETAILS { get; set; }
        public virtual DbSet<Loan_Status> Loan_Status { get; set; }
        public virtual DbSet<LOAN_TYPE> LOAN_TYPE { get; set; }
        public virtual DbSet<Manage_Loan> Manage_Loan { get; set; }
    
        public virtual int spInsertBankEmployee(string empName, Nullable<decimal> contact_Number, string email, string email_Type, string password)
        {
            var empNameParameter = empName != null ?
                new ObjectParameter("EmpName", empName) :
                new ObjectParameter("EmpName", typeof(string));
    
            var contact_NumberParameter = contact_Number.HasValue ?
                new ObjectParameter("Contact_Number", contact_Number) :
                new ObjectParameter("Contact_Number", typeof(decimal));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var email_TypeParameter = email_Type != null ?
                new ObjectParameter("Email_Type", email_Type) :
                new ObjectParameter("Email_Type", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertBankEmployee", empNameParameter, contact_NumberParameter, emailParameter, email_TypeParameter, passwordParameter);
        }
    
        public virtual ObjectResult<usp_CheckLoan_Result> usp_CheckLoan(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CheckLoan_Result>("usp_CheckLoan", cust_idParameter);
        }
    
        public virtual int usp_DeleteCustomer(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteCustomer", cust_idParameter);
        }
    
        public virtual int usp_DeleteFromApplyLoan(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteFromApplyLoan", cust_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_GetCreditLimit(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_GetCreditLimit", cust_idParameter);
        }
    
        public virtual ObjectResult<string> usp_GetCustomerFirstName(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetCustomerFirstName", cust_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_GetCustomerId(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_GetCustomerId", cust_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_GetCustomerIdAfterRegistration()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_GetCustomerIdAfterRegistration");
        }
    
        public virtual ObjectResult<string> usp_GetCustomerLastName(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetCustomerLastName", cust_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_GetEmployeeIdAfterRegistration()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_GetEmployeeIdAfterRegistration");
        }
    
        public virtual ObjectResult<string> usp_GetFirstName(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetFirstName", cust_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_GetInterestRate(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_GetInterestRate", cust_idParameter);
        }
    
        public virtual ObjectResult<string> usp_GetLastName(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetLastName", cust_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_GetLoanAmount(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_GetLoanAmount", cust_idParameter);
        }
    
        public virtual ObjectResult<string> usp_GetLoanType(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetLoanType", cust_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_GetTenure(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_GetTenure", cust_idParameter);
        }
    
        public virtual int usp_InsertApplyLoan(Nullable<int> cUSTOMER_ID, Nullable<decimal> loanAmount, string loanType, Nullable<int> tenure)
        {
            var cUSTOMER_IDParameter = cUSTOMER_ID.HasValue ?
                new ObjectParameter("CUSTOMER_ID", cUSTOMER_ID) :
                new ObjectParameter("CUSTOMER_ID", typeof(int));
    
            var loanAmountParameter = loanAmount.HasValue ?
                new ObjectParameter("LoanAmount", loanAmount) :
                new ObjectParameter("LoanAmount", typeof(decimal));
    
            var loanTypeParameter = loanType != null ?
                new ObjectParameter("LoanType", loanType) :
                new ObjectParameter("LoanType", typeof(string));
    
            var tenureParameter = tenure.HasValue ?
                new ObjectParameter("Tenure", tenure) :
                new ObjectParameter("Tenure", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertApplyLoan", cUSTOMER_IDParameter, loanAmountParameter, loanTypeParameter, tenureParameter);
        }
    
        public virtual int usp_InsertBankEmployee(string empName, Nullable<decimal> contact_Number, string email, string employee_Type, string password)
        {
            var empNameParameter = empName != null ?
                new ObjectParameter("EmpName", empName) :
                new ObjectParameter("EmpName", typeof(string));
    
            var contact_NumberParameter = contact_Number.HasValue ?
                new ObjectParameter("Contact_Number", contact_Number) :
                new ObjectParameter("Contact_Number", typeof(decimal));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var employee_TypeParameter = employee_Type != null ?
                new ObjectParameter("Employee_Type", employee_Type) :
                new ObjectParameter("Employee_Type", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertBankEmployee", empNameParameter, contact_NumberParameter, emailParameter, employee_TypeParameter, passwordParameter);
        }
    
        public virtual ObjectResult<usp_InsertCustomers_Result> usp_InsertCustomers(string first_name, string last_name, string address, string pan_num, Nullable<long> aadhar_num, Nullable<long> con_num, string email, Nullable<System.DateTime> dob, Nullable<decimal> credit_lim, Nullable<System.DateTime> last_updated_credit_date, string password)
        {
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var pan_numParameter = pan_num != null ?
                new ObjectParameter("pan_num", pan_num) :
                new ObjectParameter("pan_num", typeof(string));
    
            var aadhar_numParameter = aadhar_num.HasValue ?
                new ObjectParameter("aadhar_num", aadhar_num) :
                new ObjectParameter("aadhar_num", typeof(long));
    
            var con_numParameter = con_num.HasValue ?
                new ObjectParameter("con_num", con_num) :
                new ObjectParameter("con_num", typeof(long));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var credit_limParameter = credit_lim.HasValue ?
                new ObjectParameter("credit_lim", credit_lim) :
                new ObjectParameter("credit_lim", typeof(decimal));
    
            var last_updated_credit_dateParameter = last_updated_credit_date.HasValue ?
                new ObjectParameter("last_updated_credit_date", last_updated_credit_date) :
                new ObjectParameter("last_updated_credit_date", typeof(System.DateTime));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_InsertCustomers_Result>("usp_InsertCustomers", first_nameParameter, last_nameParameter, addressParameter, pan_numParameter, aadhar_numParameter, con_numParameter, emailParameter, dobParameter, credit_limParameter, last_updated_credit_dateParameter, passwordParameter);
        }
    
        public virtual int usp_InsertLoan(Nullable<int> lOAN_AMOUNT, Nullable<int> cUSTOMER_ID, string lOAN_TYPE, Nullable<System.DateTime> lOAN_APPROVED_DATE, Nullable<System.DateTime> dISPERSAL_DATE, Nullable<decimal> iNTEREST_RATE, Nullable<int> tENURE, Nullable<System.DateTime> eMI_START_DATE, Nullable<System.DateTime> eMI_END_DATE, Nullable<decimal> eMI_AMOUNT, Nullable<int> cREDIT_LIMIT, Nullable<System.DateTime> lAST_UPDATED_CREDIT_DATE)
        {
            var lOAN_AMOUNTParameter = lOAN_AMOUNT.HasValue ?
                new ObjectParameter("LOAN_AMOUNT", lOAN_AMOUNT) :
                new ObjectParameter("LOAN_AMOUNT", typeof(int));
    
            var cUSTOMER_IDParameter = cUSTOMER_ID.HasValue ?
                new ObjectParameter("CUSTOMER_ID", cUSTOMER_ID) :
                new ObjectParameter("CUSTOMER_ID", typeof(int));
    
            var lOAN_TYPEParameter = lOAN_TYPE != null ?
                new ObjectParameter("LOAN_TYPE", lOAN_TYPE) :
                new ObjectParameter("LOAN_TYPE", typeof(string));
    
            var lOAN_APPROVED_DATEParameter = lOAN_APPROVED_DATE.HasValue ?
                new ObjectParameter("LOAN_APPROVED_DATE", lOAN_APPROVED_DATE) :
                new ObjectParameter("LOAN_APPROVED_DATE", typeof(System.DateTime));
    
            var dISPERSAL_DATEParameter = dISPERSAL_DATE.HasValue ?
                new ObjectParameter("DISPERSAL_DATE", dISPERSAL_DATE) :
                new ObjectParameter("DISPERSAL_DATE", typeof(System.DateTime));
    
            var iNTEREST_RATEParameter = iNTEREST_RATE.HasValue ?
                new ObjectParameter("INTEREST_RATE", iNTEREST_RATE) :
                new ObjectParameter("INTEREST_RATE", typeof(decimal));
    
            var tENUREParameter = tENURE.HasValue ?
                new ObjectParameter("TENURE", tENURE) :
                new ObjectParameter("TENURE", typeof(int));
    
            var eMI_START_DATEParameter = eMI_START_DATE.HasValue ?
                new ObjectParameter("EMI_START_DATE", eMI_START_DATE) :
                new ObjectParameter("EMI_START_DATE", typeof(System.DateTime));
    
            var eMI_END_DATEParameter = eMI_END_DATE.HasValue ?
                new ObjectParameter("EMI_END_DATE", eMI_END_DATE) :
                new ObjectParameter("EMI_END_DATE", typeof(System.DateTime));
    
            var eMI_AMOUNTParameter = eMI_AMOUNT.HasValue ?
                new ObjectParameter("EMI_AMOUNT", eMI_AMOUNT) :
                new ObjectParameter("EMI_AMOUNT", typeof(decimal));
    
            var cREDIT_LIMITParameter = cREDIT_LIMIT.HasValue ?
                new ObjectParameter("CREDIT_LIMIT", cREDIT_LIMIT) :
                new ObjectParameter("CREDIT_LIMIT", typeof(int));
    
            var lAST_UPDATED_CREDIT_DATEParameter = lAST_UPDATED_CREDIT_DATE.HasValue ?
                new ObjectParameter("LAST_UPDATED_CREDIT_DATE", lAST_UPDATED_CREDIT_DATE) :
                new ObjectParameter("LAST_UPDATED_CREDIT_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertLoan", lOAN_AMOUNTParameter, cUSTOMER_IDParameter, lOAN_TYPEParameter, lOAN_APPROVED_DATEParameter, dISPERSAL_DATEParameter, iNTEREST_RATEParameter, tENUREParameter, eMI_START_DATEParameter, eMI_END_DATEParameter, eMI_AMOUNTParameter, cREDIT_LIMITParameter, lAST_UPDATED_CREDIT_DATEParameter);
        }
    
        public virtual int usp_InsertManageLoan(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertManageLoan", cust_idParameter);
        }
    
        public virtual ObjectResult<usp_SearchCustomer_Result> usp_SearchCustomer(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SearchCustomer_Result>("usp_SearchCustomer", cust_idParameter);
        }
    
        public virtual ObjectResult<usp_ShowAllLoanApplications_Result> usp_ShowAllLoanApplications()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ShowAllLoanApplications_Result>("usp_ShowAllLoanApplications");
        }
    
        public virtual ObjectResult<usp_ShowEligibleCustomers_Result> usp_ShowEligibleCustomers(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ShowEligibleCustomers_Result>("usp_ShowEligibleCustomers", cust_idParameter);
        }
    
        public virtual ObjectResult<usp_ShowManageLoan_Result> usp_ShowManageLoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ShowManageLoan_Result>("usp_ShowManageLoan");
        }
    
        public virtual int usp_UpdateApplyLoanAccept(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateApplyLoanAccept", cust_idParameter);
        }
    
        public virtual int usp_UpdateApplyLoanReject(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateApplyLoanReject", cust_idParameter);
        }
    
        public virtual int usp_UpdateApproved(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateApproved", cust_idParameter);
        }
    
        public virtual int usp_UpdateCustomer(Nullable<int> cust_id, string fIRST_NAME, string lAST_NAME, string aDDRESS, string pAN_NUMBER, Nullable<decimal> aADHAR_NUMBER, Nullable<decimal> cONTACT_NUMBER, string eMAIL, Nullable<System.DateTime> dOB, Nullable<decimal> cREDIT_LIMIT, Nullable<System.DateTime> lAST_UPDATED_CREDIT_DATE)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            var fIRST_NAMEParameter = fIRST_NAME != null ?
                new ObjectParameter("FIRST_NAME", fIRST_NAME) :
                new ObjectParameter("FIRST_NAME", typeof(string));
    
            var lAST_NAMEParameter = lAST_NAME != null ?
                new ObjectParameter("LAST_NAME", lAST_NAME) :
                new ObjectParameter("LAST_NAME", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var pAN_NUMBERParameter = pAN_NUMBER != null ?
                new ObjectParameter("PAN_NUMBER", pAN_NUMBER) :
                new ObjectParameter("PAN_NUMBER", typeof(string));
    
            var aADHAR_NUMBERParameter = aADHAR_NUMBER.HasValue ?
                new ObjectParameter("AADHAR_NUMBER", aADHAR_NUMBER) :
                new ObjectParameter("AADHAR_NUMBER", typeof(decimal));
    
            var cONTACT_NUMBERParameter = cONTACT_NUMBER.HasValue ?
                new ObjectParameter("CONTACT_NUMBER", cONTACT_NUMBER) :
                new ObjectParameter("CONTACT_NUMBER", typeof(decimal));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var cREDIT_LIMITParameter = cREDIT_LIMIT.HasValue ?
                new ObjectParameter("CREDIT_LIMIT", cREDIT_LIMIT) :
                new ObjectParameter("CREDIT_LIMIT", typeof(decimal));
    
            var lAST_UPDATED_CREDIT_DATEParameter = lAST_UPDATED_CREDIT_DATE.HasValue ?
                new ObjectParameter("LAST_UPDATED_CREDIT_DATE", lAST_UPDATED_CREDIT_DATE) :
                new ObjectParameter("LAST_UPDATED_CREDIT_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateCustomer", cust_idParameter, fIRST_NAMEParameter, lAST_NAMEParameter, aDDRESSParameter, pAN_NUMBERParameter, aADHAR_NUMBERParameter, cONTACT_NUMBERParameter, eMAILParameter, dOBParameter, cREDIT_LIMITParameter, lAST_UPDATED_CREDIT_DATEParameter);
        }
    
        public virtual int usp_UpdateCustomerDetails(Nullable<int> cust_id, string fIRST_NAME, string lAST_NAME, string aDDRESS, string pAN_NUMBER, Nullable<decimal> aADHAR_NUMBER, Nullable<decimal> cONTACT_NUMBER, Nullable<System.DateTime> dOB, Nullable<decimal> cREDIT_LIMIT, Nullable<System.DateTime> lAST_UPDATED_CREDIT_DATE)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            var fIRST_NAMEParameter = fIRST_NAME != null ?
                new ObjectParameter("FIRST_NAME", fIRST_NAME) :
                new ObjectParameter("FIRST_NAME", typeof(string));
    
            var lAST_NAMEParameter = lAST_NAME != null ?
                new ObjectParameter("LAST_NAME", lAST_NAME) :
                new ObjectParameter("LAST_NAME", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var pAN_NUMBERParameter = pAN_NUMBER != null ?
                new ObjectParameter("PAN_NUMBER", pAN_NUMBER) :
                new ObjectParameter("PAN_NUMBER", typeof(string));
    
            var aADHAR_NUMBERParameter = aADHAR_NUMBER.HasValue ?
                new ObjectParameter("AADHAR_NUMBER", aADHAR_NUMBER) :
                new ObjectParameter("AADHAR_NUMBER", typeof(decimal));
    
            var cONTACT_NUMBERParameter = cONTACT_NUMBER.HasValue ?
                new ObjectParameter("CONTACT_NUMBER", cONTACT_NUMBER) :
                new ObjectParameter("CONTACT_NUMBER", typeof(decimal));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var cREDIT_LIMITParameter = cREDIT_LIMIT.HasValue ?
                new ObjectParameter("CREDIT_LIMIT", cREDIT_LIMIT) :
                new ObjectParameter("CREDIT_LIMIT", typeof(decimal));
    
            var lAST_UPDATED_CREDIT_DATEParameter = lAST_UPDATED_CREDIT_DATE.HasValue ?
                new ObjectParameter("LAST_UPDATED_CREDIT_DATE", lAST_UPDATED_CREDIT_DATE) :
                new ObjectParameter("LAST_UPDATED_CREDIT_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateCustomerDetails", cust_idParameter, fIRST_NAMEParameter, lAST_NAMEParameter, aDDRESSParameter, pAN_NUMBERParameter, aADHAR_NUMBERParameter, cONTACT_NUMBERParameter, dOBParameter, cREDIT_LIMITParameter, lAST_UPDATED_CREDIT_DATEParameter);
        }
    
        public virtual int usp_UpdateLoan(Nullable<int> lOAN_AMOUNT, Nullable<int> cUSTOMER_ID, string lOAN_TYPE, Nullable<System.DateTime> lOAN_APPROVED_DATE, Nullable<System.DateTime> dISPERSAL_DATE, Nullable<decimal> iNTEREST_RATE, Nullable<decimal> tENURE, Nullable<System.DateTime> eMI_START_DATE, Nullable<System.DateTime> eMI_END_DATE, Nullable<decimal> eMI_AMOUNT, Nullable<int> cREDIT_LIMIT, Nullable<System.DateTime> lAST_UPDATED_CREDIT_DATE, Nullable<int> cUSTOMER_ASSET_ID)
        {
            var lOAN_AMOUNTParameter = lOAN_AMOUNT.HasValue ?
                new ObjectParameter("LOAN_AMOUNT", lOAN_AMOUNT) :
                new ObjectParameter("LOAN_AMOUNT", typeof(int));
    
            var cUSTOMER_IDParameter = cUSTOMER_ID.HasValue ?
                new ObjectParameter("CUSTOMER_ID", cUSTOMER_ID) :
                new ObjectParameter("CUSTOMER_ID", typeof(int));
    
            var lOAN_TYPEParameter = lOAN_TYPE != null ?
                new ObjectParameter("LOAN_TYPE", lOAN_TYPE) :
                new ObjectParameter("LOAN_TYPE", typeof(string));
    
            var lOAN_APPROVED_DATEParameter = lOAN_APPROVED_DATE.HasValue ?
                new ObjectParameter("LOAN_APPROVED_DATE", lOAN_APPROVED_DATE) :
                new ObjectParameter("LOAN_APPROVED_DATE", typeof(System.DateTime));
    
            var dISPERSAL_DATEParameter = dISPERSAL_DATE.HasValue ?
                new ObjectParameter("DISPERSAL_DATE", dISPERSAL_DATE) :
                new ObjectParameter("DISPERSAL_DATE", typeof(System.DateTime));
    
            var iNTEREST_RATEParameter = iNTEREST_RATE.HasValue ?
                new ObjectParameter("INTEREST_RATE", iNTEREST_RATE) :
                new ObjectParameter("INTEREST_RATE", typeof(decimal));
    
            var tENUREParameter = tENURE.HasValue ?
                new ObjectParameter("TENURE", tENURE) :
                new ObjectParameter("TENURE", typeof(decimal));
    
            var eMI_START_DATEParameter = eMI_START_DATE.HasValue ?
                new ObjectParameter("EMI_START_DATE", eMI_START_DATE) :
                new ObjectParameter("EMI_START_DATE", typeof(System.DateTime));
    
            var eMI_END_DATEParameter = eMI_END_DATE.HasValue ?
                new ObjectParameter("EMI_END_DATE", eMI_END_DATE) :
                new ObjectParameter("EMI_END_DATE", typeof(System.DateTime));
    
            var eMI_AMOUNTParameter = eMI_AMOUNT.HasValue ?
                new ObjectParameter("EMI_AMOUNT", eMI_AMOUNT) :
                new ObjectParameter("EMI_AMOUNT", typeof(decimal));
    
            var cREDIT_LIMITParameter = cREDIT_LIMIT.HasValue ?
                new ObjectParameter("CREDIT_LIMIT", cREDIT_LIMIT) :
                new ObjectParameter("CREDIT_LIMIT", typeof(int));
    
            var lAST_UPDATED_CREDIT_DATEParameter = lAST_UPDATED_CREDIT_DATE.HasValue ?
                new ObjectParameter("LAST_UPDATED_CREDIT_DATE", lAST_UPDATED_CREDIT_DATE) :
                new ObjectParameter("LAST_UPDATED_CREDIT_DATE", typeof(System.DateTime));
    
            var cUSTOMER_ASSET_IDParameter = cUSTOMER_ASSET_ID.HasValue ?
                new ObjectParameter("CUSTOMER_ASSET_ID", cUSTOMER_ASSET_ID) :
                new ObjectParameter("CUSTOMER_ASSET_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateLoan", lOAN_AMOUNTParameter, cUSTOMER_IDParameter, lOAN_TYPEParameter, lOAN_APPROVED_DATEParameter, dISPERSAL_DATEParameter, iNTEREST_RATEParameter, tENUREParameter, eMI_START_DATEParameter, eMI_END_DATEParameter, eMI_AMOUNTParameter, cREDIT_LIMITParameter, lAST_UPDATED_CREDIT_DATEParameter, cUSTOMER_ASSET_IDParameter);
        }
    
        public virtual int usp_UpdateRejected(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateRejected", cust_idParameter);
        }
    
        public virtual ObjectResult<usp_ViewCustomer_Result> usp_ViewCustomer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ViewCustomer_Result>("usp_ViewCustomer");
        }
    
        public virtual ObjectResult<usp_ViewCustomerDetails_Result> usp_ViewCustomerDetails(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ViewCustomerDetails_Result>("usp_ViewCustomerDetails", cust_idParameter);
        }
    
        public virtual ObjectResult<usp_ViewLoanStatus_Result> usp_ViewLoanStatus(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ViewLoanStatus_Result>("usp_ViewLoanStatus", cust_idParameter);
        }
    }
}
